name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format
        run: bun run format

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
